config/routes.rb
Rails.application.routes.draw do

  root 'resources#index'
  resources :resources
  #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resource.rb
class Resource < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController

  def index
    @resources = Resource.all
  end

  def new
    @resource = Resource.new
  end

  def create
    Resource.create(resource_params)
    redirect_to root_path
  end

  private

  def resource_params
    params.require(:resource).permit(:name, :description, :rating)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmeriResource</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/resources/index.html.erb
<h1> AmeriResources </h1>
<br />

<h2> Resources for current AmeriCorps and AmeriCorps Alum</h2>
<br />

<div class = "btn btn-secondary">
  <%= link_to "Add a Resource", new_resource_path %>
</div>
<br />
<br />

<div class = col-5>
  <div class = 'booyah-box'>
    <% @resources.each do |resource| %>
      <h3><%= resource.name %></h3>
      <br />
      <h3><%= resource.description %></h3>
      <h3><%= resource.rating %></h3>
    <% end %>
    <br />
  </div>
<div>



app/views/resources/new.html.erb
<div class = "booyah-box">
  <h1> Add a New Resource </h1>
  <%= simple_form_for @resource do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :rating %>
    <%= f.submit 'Share', class: 'btn btn-info' %>
  <% end %>
  <br />
</div>